### ISSUE TITLE
Installing the Extension in CiviCRM 5.57.3 gives a critical Error

### ISSUE THREAD

**Issue by maxhaslbeck** [davidjosephhayes/CiviCRM-Default-Dashlets#3]
Hi there,

I tried installing the CiviCRM Default Dashlets extension on my CiviCRM system of version 5.57.3.
It fails with an critical Error.
![grafik](https://user-images.githubusercontent.com/1205132/216149264-a1c221cd-e6b5-4460-b328-9e74b7652f33.png)

If I try with the [fork of this repository by tobiashreiter](https://github.com/tobiashreiter/CiviCRM-Default-Dashlets), it in deed works. So please consider using [their fix](https://github.com/tobiashreiter/CiviCRM-Default-Dashlets/commit/3ff767aba1a34ae01dab12dcd34acb1fb2828904).

Also please consider updating https://civicrm.org/extensions/default-dashlets
and updating the "Compatible with" field.

cheers

**Comment by davidjosephhayes** [comment]
Hey @maxhaslbeck, I totally forgot this repo existed. Feel free to submit any PR's or I can add you as a Collaborator if you are interested in maintaining the extension in the future.

As for the CiviCRM Extension listing, no quite sure how it got there or how to modify it. It does not show in my civicrm.org account.

**Comment by maxhaslbeck** [comment]
I felt free and submitted a PR, but I dont know whether it was done correctly :)

As for the CiviCRM Extension listing, I also have no clue how to modify it.  the "compatible with" field might be located in the compatibility tag 
https://github.com/davidjosephhayes/CiviCRM-Default-Dashlets/blob/15b7da689f505eff4fe5e6b6a40d666da98f45bd/info.xml#L20-L22

**Comment by davidjosephhayes** [comment]
PR looks great!

**Comment by davidjosephhayes** [comment]
Seems reasonable that chunk of XML would determine that. If the extension still works for you in the current version of current version of CiviCRM, feel free to update it.

**Comment by wintermoor** [comment]
Hm, sorry to say that this fix doesn't fix the problem on CiviCRM 6.1.2 with WordPress: can't install this extension. 

It's something with Smarty version 5, but I don't know how to fix it: 

```
Ein Fehler vom Typ E_ERROR wurde in der Zeile 37 der Datei /var/www/vhosts/event.XXXXXX.de/httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php verursacht. Fehlermeldung: Uncaught Error: Cannot access protected property Smarty\Smarty::$template_dir in /var/www/vhosts/event.XXXXXX.de/httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php:37
Stack trace:
#0 /var/www/vhosts/event.XXXXXX.de/httpdocs/wp-content/uploads/civicrm/ext/CiviCRM-Default-Dashlets-master/defaultdashlets.civix.php(22): Smarty->__get()
#1 /var/www/vhosts/event.XXXXXX.de/httpdocs/wp-content/uploads/civicrm/ext/CiviCRM-Default-Dashlets-master/defaultdashlets.civix.php(52): _defaultdashlets_civix_civicrm_config()
```
